version: "2"

services:
  beckend:
    build: .
    ports:
      - 4004:4004
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    environment:
      PORT: 4004