version: "2"

services:
  # backend:
  #   build: .
  #   ports:
  #     - 4004:4004
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     DATABASE_URL: postgres://postgres@postgres/comments_dev
  #     PORT: 4004
  #   command: npm run start:docker
  #   restart: always
  #   depends_on:
  #     - postgres

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comments
      POSTGRES_HOST_AUTH_METHOD: trust

